//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Insurancesystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Car
    {
        public int UserID { get; set; }
        public string ModeofUse { get; set; }
        public Nullable<int> Car1 { get; set; }
        public Nullable<double> CarValue { get; set; }
    }
}
