//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Insurancesystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Car
    {
        public int CarID { get; set; }
        public string ModeOfUse { get; set; }
        public int Car1 { get; set; }
        public double CarValue { get; set; }
        public int CarRegisternumber { get; set; }
        public int UserID { get; set; }
    
        public virtual USER USER { get; set; }
    }
}
