//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Insurancesystem.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class InsuranceDBEntities1 : DbContext
    {
        public InsuranceDBEntities1()
            : base("name=InsuranceDBEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Car> Cars { get; set; }
        public virtual DbSet<Claim> Claims { get; set; }
        public virtual DbSet<CusContact> CusContacts { get; set; }
        public virtual DbSet<Motorbike> Motorbikes { get; set; }
        public virtual DbSet<USER> USERs { get; set; }

        public System.Data.Entity.DbSet<Insurancesystem.ViewModel.Userlogin> Userlogins { get; set; }

        public System.Data.Entity.DbSet<Insurancesystem.ViewModel.Registerview> Registerviews { get; set; }

        public System.Data.Entity.DbSet<Insurancesystem.ViewModel.UserView> UserViews { get; set; }

        public System.Data.Entity.DbSet<Insurancesystem.ViewModel.ModifyUser> ModifyUsers { get; set; }

        public System.Data.Entity.DbSet<Insurancesystem.ViewModel.UserClaim> UserClaims { get; set; }
    }
}
