//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Insurancesystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MotorBike
    {
        public int UserID { get; set; }
        public string ModeOfUse { get; set; }
        public Nullable<int> MotorRegisternumber { get; set; }
        public Nullable<int> MotorValue { get; set; }
    }
}
