//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Insurancesystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Motorbike
    {
        public int MotorID { get; set; }
        public string ModeOfUse { get; set; }
        public int MotorRegisNumber { get; set; }
        public int MotorValue { get; set; }
        public int UserID { get; set; }
    
        public virtual User User { get; set; }
    }
}
